name: Deploy ARM Template
#npc22222222
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Update Parameters File
      run: |
        # Ensure all required secrets are set
        if [ -z "${{ secrets.LOCATION }}" ] || [ -z "${{ secrets.STORAGE_ACCOUNT_NAME }}" ] || [ -z "${{ secrets.STORAGE_ACCOUNT_TYPE }}" ] || [ -z "${{ secrets.SERVER_FARM_NAME }}" ] || [ -z "${{ secrets.APPLICATION_INSIGHTS_NAME }}" ]; then
          echo "One or more required secrets are not set"
          exit 1
        fi
        
        # Create a temporary parameters file with updated values
        jq --arg location "${{ secrets.LOCATION }}" \
           --arg storageAccountName "${{ secrets.STORAGE_ACCOUNT_NAME }}" \
           --arg storageAccountType "${{ secrets.STORAGE_ACCOUNT_TYPE }}" \
           --arg serverFarmName "${{ secrets.SERVER_FARM_NAME }}" \
           --arg applicationInsightsName "${{ secrets.APPLICATION_INSIGHTS_NAME }}" \
           '.parameters.location.value = $location | .parameters.storageAccountName.value = $storageAccountName | .parameters.storageAccountType.value = $storageAccountType | .parameters.serverFarmName.value = $serverFarmName | .parameters.applicationInsightsName.value = $applicationInsightsName' \
           .github/workflows/parameters2.json > updated_parameters2.json

        cat updated_parameters2.json

    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: .github/workflows/template2.json
        parameters: updated_parameters2.json
