name: Deploy ARM Template
#npc22222222
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Check if LOCATION secret is set
      run: |
        if [ -z "${{ secrets.LOCATION }}" ]; then
          echo "LOCATION secret is not set"
          exit 1
        fi

    - name: Update Parameters File
      run: |
        cat .github/workflows/parameters2.json
        jq --arg location "${{ secrets.LOCATION }}" '.parameters.location.value = $location' .github/workflows/parameters2.json > updated_parameters2.json
        cat updated_parameters2.json

    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: .github/workflows/template2.json
        parameters: updated_parameters2.json
