name: Deploy ARM Template

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: .github/workflows/template2.txt
        parameters: .github/workflows/template2.txt
<<<<<<< HEAD
        
        inlineScript: |
=======
inlineScript: |
>>>>>>> 09395d531e5d156a4dfa7df09e553ffb510e36f2
            az deployment group create \
              --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
              --template-file deploy-CI-CD/.github/workflows/template2.txt \
              --parameters storageAccountName=${{ secrets.STORAGE_ACCOUNT_NAME }} \
                           location=${{ secrets.LOCATION }} \
                           storageAccountType=${{ secrets.STORAGE_ACCOUNT_TYPE }} \
                           serverFarmName=${{ secrets.SERVER_FARM_NAME }} \
<<<<<<< HEAD
                           applicationInsightsName=${{ secrets.APPLICATION_INSIGHTS_NAME }}
=======
                           applicationInsightsName=${{ secrets.APPLICATION_INSIGHTS_NAME }}
>>>>>>> 09395d531e5d156a4dfa7df09e553ffb510e36f2
