name: Deploy ARM Template
#npc222222222
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Update Parameters File
      run: |
        jq --arg location "${{ secrets.LOCATION }}" '.parameters.location.value = $location' .github/workflows/parameters2.json > updated_parameters2.json

    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: .github/workflows/template2.json
        parameters: updated_parameters2.json
